---
title: "Regresinė Analizė"
author: "Vainius Gataveckas, Matas Gaulia, Dovydas Martinkus"
output:
   html_document: default
---


```{r, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)
```

```{r}
library(tidyverse)
library(car)
library(janitor)
x <- read_csv("life.csv") %>% clean_names()
```

### Tikslas: prognozuoti vidutinę gyvenimo trukmę šalyje pagal tam tikrus sveikatos rodiklius


```{r}
set.seed(150)
transform_1<- function(x) {
  x %>%
  group_by(country) %>%
  fill(everything(), .direction = "up") %>%
  dplyr::select(-c(1, 3), -population, -percentage_expenditure) %>%
  drop_na() %>%
  ungroup() %>%
  dplyr::select(-1)
}

x <- transform_1(x)

x_1 <- x %>% filter(year == max(year)) %>% select(-1)

# atskiri duomenys, patikrinti kaip gautas galutinis modelis prognozuoja reikšmes
x_predict <- x %>% filter(year != max(year)) %>% slice_sample(n=10) %>% select(-1)


# kaikurių kovariančių priklausomybę nėra tiesinė
x_1 %>% pivot_longer(-1) %>% ggplot(aes(x=value,y=life_expectancy)) + facet_wrap(vars(name),scales="free") + geom_point() + geom_smooth(method="lm") + theme_minimal()

model <- lm(life_expectancy ~ ., data = x_1)
crPlots(model)
```



```{r}
transform_2 <- function(x) {
    x %>% 
    mutate(gdp = log(gdp),
    infant_deaths = log(infant_deaths + 1),
    measles = log(measles + 1),
    total_expenditure = log(total_expenditure + 1),
    under_five_deaths = log(under_five_deaths + 1)
  )
}

# transformuojamos kaikurios kovariantės
x_2 <- transform_2(x_1)
x_predict <- transform_2(x_predict)


# Kintamųjų tiesinis ryšys patikrinamas dar kartą
x_2 %>% pivot_longer(-1) %>% ggplot(aes(x=value,y=life_expectancy)) + facet_wrap(vars(name),scales="free") + geom_point() + geom_smooth(method="lm") + theme_minimal()


write.csv(x_2, "life_modified.csv")

# Sukuriamas modelis
model <- lm(life_expectancy ~ ., data = x_2)
```


### Modelio prielaidos
```{r}
# Tikrinamas liekanų normalumas, homoskadiškumas, liekanų nepriklausomumas, išskirtys
plot(model)
plot(cooks.distance(model))
plot(hatvalues(model))

# Liekanų normalumo testas
shapiro.test(residuals(model))


# Homoskadiškumo testas
library(lmtest)
bptest(model)
```


```{r}
crPlots(model)
avPlots(model)
```

```{r}
anova(model) # Tikrinama hipotezė H0: beta_1 = beta_2 = ... = 0
```


### Modelio parinkimas


```{r}
# Požinksninė regresija
library(RcmdrMisc)
model_2 <- stepwise(model)
```


### Parametrų vertinimas ir interpretacija

```{r}
# Koeficientai
summary(model_2) 
  # Visų koeficientų interpretacija paprasta,
  # nes pažingsnine regresija neišrinkti transformuoti kintamieji
library(lm.beta)
# Standartizuoti koeficientai
lm.beta(model_2)

# Pasikliovimo interalai
confint(model_2)

# Kovariancių įtaka vizualizuota
library(effects)
plot(predictorEffects(model_2))
```


### Multikolinearumas

```{r}
vars <- dplyr::select(x_2, c(adult_mortality, hepatitis_b, total_expenditure,
  hiv_aids, income_composition_of_resources, life_expectancy))

#library(psych)
#corr.test(vars)

#dalinės koreliacijos
library(ppcor)
pcor(vars)$estimate

# Variance inflation factor
vif(model_2)
```



### Modelio tinkamumo analizė
```{r}

summary(model_2) 
  # R-squared = 0.897
  # Adj R-squared = 0.892

plot_predictions <- function(x,y) {
  predictions <- predict(x,newdata = y, interval = "prediction")
  predictions <- as_tibble(predictions) %>% mutate(n = 1:nrow(predictions))

  
  predictions_points <- y %>%
  mutate(pred = predictions) %>% 
  unnest(pred) %>%
  dplyr::select(1,last_col(3),last_col(2),last_col(1),last_col(0)) %>%
  pivot_longer(c(1,2))
  

  ggplot(predictions) + 
  geom_linerange(aes(x=n,ymin=lwr,ymax=upr)) + 
  geom_point(data=predictions_points,aes(x=n,y=value,color=name),size = 4) + 
  scale_x_discrete("Observation") +
  scale_y_continuous("Life Expectancy") + 
  theme_minimal(base_size = 16) + 
  scale_color_brewer("",palette = "Set1") 
}

# Atliekamos kelios pavyzdinės prognozės
plot_predictions(model_2,x_predict)
```
